export const ListOfOrchids = [
    {
        id: '1',
        name: 'Moth Orchid',
        rating: 5,
        isSpecial: true,
        isNatural: true,
        image: '/image/1-moth-orchid.png',
        color: 'Pink & White',
        numberOfLike: 230,
        origin: 'Southeast Asia',
        category: 'Phalaenopsis'
    },
    {
        id: '2',
        name: 'Boat Orchid',
        rating: 4,
        isSpecial: false,
        isNatural: true,
        image: '/image/2-boat-orchids.png',
        color: 'Golden Yellow',
        numberOfLike: 185,
        origin: 'Vietnam',
        category: 'Cymbidium'
    },
    {
        id: '3',
        name: 'Maxillaria Orchid',
        rating: 4,
        isSpecial: false,
        isNatural: true,
        image: '/image/3-maxillaria-orchid.png',
        color: 'Deep Crimson Red',
        numberOfLike: 140,
        origin: 'Central America',
        category: 'Maxillaria'
    },
    {
        id: '4',
        name: "Lady's Slipper Orchid",
        rating: 5,
        isSpecial: true,
        isNatural: true,
        image: '/image/4-lady-slippe-orchid.png',
        color: 'Yellow & Spotted Brown',
        numberOfLike: 310,
        origin: 'Southeast Asia',
        category: 'Paphiopedilum'
    },
    {
        id: '5',
        name: 'Butterfly Orchid',
        rating: 5,
        isSpecial: true,
        isNatural: false,
        image: '/image/5-psychopsis-orchid.png',
        color: 'Bright Yellow & Chestnut',
        numberOfLike: 275,
        origin: 'South America',
        category: 'Psychopsis'
    },
    {
        id: '6',
        name: 'Dendrobium Orchid',
        rating: 4,
        isSpecial: false,
        isNatural: true,
        image: '/image/6-dendrobium-orchid.png',
        color: 'Purple & White',
        numberOfLike: 195,
        origin: 'Himalayas',
        category: 'Dendrobium'
    },
    {
        id: '7',
        name: 'Cattleya Queen Orchid',
        rating: 5,
        isSpecial: true,
        isNatural: false,
        image: '/image/7-cattleya-orchid.png',
        color: 'Magenta & Lavender',
        numberOfLike: 420,
        origin: 'Brazil',
        category: 'Cattleya'
    },
    {
        id: '8',
        name: 'Ghost Orchid',
        rating: 5,
        isSpecial: true,
        isNatural: true,
        image: '/image/8-ghost-orchid.png',
        color: 'Translucent White',
        numberOfLike: 580,
        origin: 'Florida & Cuba',
        category: 'Dendrophylax'
    },
    {
        id: '9',
        name: 'Blue Vanda Orchid',
        rating: 5,
        isSpecial: true,
        isNatural: true,
        image: '/image/9-vanda-orchid.png',
        color: 'Royal Blue Violet',
        numberOfLike: 360,
        origin: 'Thailand',
        category: 'Vanda'
    },
    {
        id: '10',
        name: 'Zygopetalum Orchid',
        rating: 4,
        isSpecial: false,
        isNatural: true,
        image: '/image/10-zygopetalum-orchid.png',
        color: 'Spotted Purple & Green',
        numberOfLike: 160,
        origin: 'Peru',
        category: 'Zygopetalum'
    },
    {
        id: '11',
        name: 'Lady of the Night',
        rating: 4,
        isSpecial: false,
        isNatural: true,
        image: '/image/11-brassavola-orchid.png',
        color: 'Greenish White',
        numberOfLike: 210,
        origin: 'Mexico',
        category: 'Brassavola'
    },
    {
        id: '12',
        name: 'Dancing Lady Orchid',
        rating: 4,
        isSpecial: false,
        isNatural: false,
        image: '/image/12-oncidium-orchid.png',
        color: 'Canary Yellow',
        numberOfLike: 245,
        origin: 'Central America',
        category: 'Oncidium'
    },
    {
        id: '13',
        name: 'Crucifix Orchid',
        rating: 3,
        isSpecial: false,
        isNatural: true,
        image: '/image/13-epidendrum-orchid.png',
        color: 'Vibrant Orange-Red',
        numberOfLike: 135,
        origin: 'Colombia',
        category: 'Epidendrum'
    },
    {
        id: '14',
        name: 'Odontoglossum Orchid',
        rating: 4,
        isSpecial: false,
        isNatural: true,
        image: '/image/14-odontoglossum-orchid.png',
        color: 'Tiger Striped Bronze',
        numberOfLike: 170,
        origin: 'Andes Mountains',
        category: 'Odontoglossum'
    },
    {
        id: '15',
        name: "Nun's Orchid",
        rating: 4,
        isSpecial: false,
        isNatural: true,
        image: '/image/15-phaius-orchid.png',
        color: 'Copper Brown & Violet',
        numberOfLike: 155,
        origin: 'Madagascar',
        category: 'Phaius'
    },
    {
        id: '16',
        name: 'Jewel Orchid',
        rating: 5,
        isSpecial: true,
        isNatural: true,
        image: '/image/16-ludisia-orchid.png',
        color: 'Velvet Black & Pinstripe Red',
        numberOfLike: 490,
        origin: 'Southeast Asia',
        category: 'Ludisia'
    }
];


